# Generated by Django 3.1.1 on 2020-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0005_auto_20200919_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_informationinfo',
            name='Basic_information_school_cover_img',
            field=models.ImageField(upload_to=' school_cover//'),
        ),
        migrations.AlterField(
            model_name='basic_informationinfo',
            name='Basic_information_school_upload_brochure',
            field=models.FileField(upload_to='school_pdf/'),
        ),
    ]
