# Generated by Django 3.1.1 on 2020-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0006_auto_20200919_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactaddressinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optradioaddr', models.CharField(max_length=200)),
                ('addrcountry', models.CharField(max_length=200)),
                ('addrstate', models.CharField(max_length=200)),
                ('addrDistrict', models.CharField(max_length=200)),
                ('addrmain_toen_area', models.CharField(max_length=200)),
                ('addrsub_area', models.CharField(max_length=200)),
                ('addrlanmark', models.CharField(max_length=200)),
                ('addr_addres', models.CharField(max_length=200)),
                ('addr_pincode', models.CharField(max_length=200)),
                ('addr_location', models.CharField(max_length=200)),
                ('addr_name_fap', models.CharField(max_length=200)),
                ('addr_name_fap_distance', models.CharField(max_length=200)),
                ('addr_name_fap_time', models.CharField(max_length=200)),
                ('addr_name_fap_latidue', models.CharField(max_length=200)),
                ('addr_name_fap_longatitide', models.CharField(max_length=200)),
                ('addr_name_rail_name1', models.CharField(max_length=200)),
                ('addr_name_rail_distance', models.CharField(max_length=200)),
                ('addr_name_rail_time', models.CharField(max_length=200)),
                ('addr_name_rail_name2', models.CharField(max_length=200)),
                ('addr_name_rail_distance2', models.CharField(max_length=200)),
                ('addr_name_rail_time2', models.CharField(max_length=200)),
                ('addr_name_bus_name', models.CharField(max_length=200)),
                ('addr_name_bus_distancr', models.CharField(max_length=200)),
                ('addr_name_bus_time', models.CharField(max_length=200)),
                ('addr_nus_nof', models.CharField(max_length=200)),
                ('addr_nus_to_railway', models.CharField(max_length=200)),
                ('addr_nus_to_school', models.CharField(max_length=200)),
                ('addr_contact_name', models.CharField(max_length=200)),
                ('addr_contact_mobno', models.CharField(max_length=200)),
                ('addr_contact_email', models.CharField(max_length=200)),
                ('addr_contact_designation', models.CharField(max_length=200)),
                ('addr_contact_principal_name', models.CharField(max_length=200)),
                ('addr_contact_principal_mobno', models.CharField(max_length=200)),
                ('addr_contact_principal_email', models.CharField(max_length=200)),
                ('addr_contact_principal_mobhs', models.CharField(max_length=200)),
                ('addr_chairman_dir_name', models.CharField(max_length=200)),
                ('addr_chairman_dir_mobno', models.CharField(max_length=200)),
                ('addr_chairman_dir_email', models.CharField(max_length=200)),
                ('addr_chairman_dir_hideshow', models.CharField(max_length=200)),
                ('addr_official_name', models.CharField(max_length=200)),
                ('addr_official_email', models.CharField(max_length=200)),
                ('addr_official_fax', models.CharField(max_length=200)),
                ('schooldescription', models.CharField(max_length=200)),
                ('schooldescription_title', models.CharField(max_length=200)),
                ('schooldescription_title_topic', models.CharField(max_length=200)),
            ],
        ),
    ]
