# Generated by Django 3.1.1 on 2020-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0007_contactaddressinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='pic.png', null=True, upload_to='images/'),
        ),
    ]
