# Generated by Django 3.1.1 on 2020-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0008_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Col_Basic_informationinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_information_colleges_name', models.CharField(max_length=200)),
                ('Basic_information_colleges_short_name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('Basic_information_tag_line_of_colleges', models.CharField(max_length=200)),
                ('Basic_information_colleges_url', models.CharField(max_length=200)),
                ('Basic_information_colleges_logo', models.ImageField(upload_to='images/')),
                ('Basic_information_colleges_trusty_socity', models.CharField(max_length=200)),
                ('Basic_information_colleges_cover_img', models.ImageField(upload_to=' school_cover//')),
                ('Basic_information_colleges_upload_brochure', models.FileField(upload_to='school_pdf/')),
            ],
        ),
    ]
