# Generated by Django 3.1.1 on 2020-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0009_col_basic_informationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='pic.png', null=True, upload_to='images/'),
        ),
    ]
