# Generated by Django 3.1.1 on 2020-10-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0011_auto_20201003_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddressinfo',
            name='detailse1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fime1223.customer'),
        ),
    ]
