# Generated by Django 3.1.1 on 2020-10-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0012_contactaddressinfo_detailse1'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='image',
            field=models.ImageField(default='pic.png', null=True, upload_to='images/'),
        ),
    ]
